### ISSUE TITLE
auto-install-base-components src fails on FreeBSD 13.0-RELEASE 

### ISSUE THREAD

**Issue by hapygallagher** [outpaddling/auto-admin#6]
For my system it is trying to fetch this location:

ftp.freebsd.org/pub/FreeBSD/snapshots/arm64/13.0-RELEASE/src.txz

and I believe the correct path is:

ftp.freebsd.org/pub/FreeBSD/snapshots/arm64/13.0-STABLE/src.txz

**Comment by hapygallagher** [comment]
ah I was reading the script incorrectly, it seems to be incorrectly detecting the RELEASE, will keep testing

**Comment by yzgyyang** [comment]
This also failed for me on 13.0R arm64.

![image](https://user-images.githubusercontent.com/16748524/148030961-615fad8d-9fed-4afc-bb25-86c240dbf7e4.png)

**Comment by yzgyyang** [comment]
So the problem is:

ftp://ftp.freebsd.org/pub/FreeBSD/snapshots/ contains -STABLE src.txz
ftp://ftp.freebsd.org/pub/FreeBSD/releases/ contains -RELEASE src.txz

The script was looking at the wrong place.

**Comment by outpaddling** [comment]
Fixed in https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=261386.
Sorry for the delay.  For some reason I'm not seeing notifications for these Github issues.  Will investigate...

**Comment by yzgyyang** [comment]
I feel like the logic is still not right, but I could be wrong... Please see #7.

**Comment by outpaddling** [comment]
Have you tested the latest?  It works for me on -RELEASE and -CURRENT.
